---
- name: Ubuntu
  when: ansible_distribution == 'Ubuntu'
  include: ubuntu.yml

- name: Fedora
  when: ansible_distribution == 'Fedora'
  include: fedora.yml

- name: RedHat (ex-Fedora)
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'
  include: redhat.yml

