---
- name: add virtualbox rpm key
  rpm_key: >
    key='https://www.virtualbox.org/download/oracle_vbox.asc'
    state=present

- name: add virtualbox yum repo
  get_url: >
    url='http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo'
    dest=/etc/yum.repos.d/virtualbox.repo
    owner=root
    group=root
    mode=644

- name: install virtualbox
  package: >
    name=VirtualBox-{{virtualbox_version}}
    state=latest

- name: install vbox drivers...
  command: /usr/lib/virtualbox/vboxdrv.sh setup

