---
- name: (Ubuntu) virtualbox dependencies
  apt: name={{ item }}
  with_items:
    - dkms
    - libsdl-ttf2.0-0
    - libsdl1.2debian

- name : (Ubuntu) add virtualbox apt key
  apt_key:
    url: "{{ apt_virtualbox_repo_key_1 }}"
    id: "{{ apt_virtualbox_repo_key_1_id }}"
    state: present

- name : (Ubuntu) add virtualbox apt key
  apt_key:
    url: "{{ apt_virtualbox_repo_key_2 }}"
    id: "{{ apt_virtualbox_repo_key_2_id }}"
    state: present

- name: add virtualbox apt repository
  apt_repository:
    repo: "{{ apt_virtualbox_repo }}"
    update_cache: yes
    mode: 0644

- name: install virtualbox
  apt: name=virtualbox-{{virtualbox_version}}

